Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices
Imports System.Runtime.CompilerServices

'------------------------------------------------------------------------------
' <auto-generated>
'   This code was generated by a tool.
'   Runtime Version:2.0.50727.5448
'
'   Changes to this file may cause incorrect behavior and will be lost if
'   the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

<Assembly: CLSCompliantAttribute(False)>
<Assembly: AssemblyVersionAttribute("1.0.0.0")>
<Assembly: AssemblyFileVersionAttribute("1.0.0.0")>
<Assembly: AssemblyInformationalVersionAttribute("1.0.0.0-default-dev-local")>
<Assembly: AssemblyTitleAttribute("Copyright (c) 2017, Relativity ODA LLC")>
<Assembly: AssemblyDescriptionAttribute("Template")>
<Assembly: AssemblyCopyrightAttribute("© Relativity")>
<Assembly: AssemblyCompanyAttribute("Relativity ODA LLC")>
<Assembly: AssemblyProductAttribute("Relativity")>